// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using IntersectionFinder.Domain.Entities;

namespace IntersectionFinder.Infrastructure;

public partial class IntersectionsContext : DbContext
{
    public IntersectionsContext(DbContextOptions<IntersectionsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Rectangle> Rectangles { get; set; }

    public virtual DbSet<RectangleSegment> RectangleSegments { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Rectangle>(entity =>
        {
            entity.ToTable("Rectangle")
                .HasKey(e => e.RectangleId);
            
            entity.Property(e => e.RectangleId).ValueGeneratedNever();
            entity.Property(e => e.RectangleName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Geometry).HasColumnType("geometry");
        });
     
        modelBuilder.Entity<RectangleSegment>(entity =>
        {
            entity.HasKey(e => e.RectangleSegmentId).HasName("PK_RectanleSegment");

            entity.ToTable("RectangleSegment");

            entity.HasOne(d => d.Rectangle).WithMany(p => p.RectangleSegments)
                .HasForeignKey(d => d.RectangleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RectangleSegment_Rectangle");
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}